USE [Recruit_DB]
GO

/****** Object:  Table [dbo].[T_OFERTA_RECLUTADOR]    Script Date: 13/4/2018 14:31:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_OFERTA_RECLUTADOR](
	[PKOFERTATRABAJO] [int] NOT NULL,
	[PKRECLUTADOR] [int] NOT NULL,
 CONSTRAINT [PK_T_OFERTA_RECLUTADOR] PRIMARY KEY CLUSTERED 
(
	[PKOFERTATRABAJO] ASC,
	[PKRECLUTADOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


