USE [Recruit_DB]
GO

/****** Object:  Table [dbo].[T_REC_OFERTA_TRABAJO]    Script Date: 13/4/2018 14:32:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_REC_OFERTA_TRABAJO](
	[PKOFERTATRABAJO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[LABORES] [varchar](200) NULL,
	[IDIOMA] [varchar](20) NULL,
	[NIVEL_IDIOMA] [int] NULL,
	[CONOCIMIENTOS_REQ] [varchar](200) NULL,
	[CONOCIMIENTOS_DES] [varchar](200) NULL,
	[BENEFICIOS_LAB] [varchar](200) NOT NULL,
	[SALARIO] [numeric](13, 2) NULL,
	[EMPRESA] [int] NULL,
 CONSTRAINT [PK_T_REC_OFERTAS_TRABAJO] PRIMARY KEY CLUSTERED 
(
	[PKOFERTATRABAJO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


